pipeline { 
  agent any
  
  tools {
    jdk 'java-17'
    maven 'maven'
  }
  
  stages {
    stage('Git Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/anooptm1999/git-practice.git'
      }
    }

    stage('Change Directory') {
      steps {
        // Change to the directory where the pom.xml is located
        dir('project') { 
          sh 'mvn compile'
        }
      }
    }

    stage('Build') {
      steps {
        dir('project') {
          sh 'mvn clean install'
        }
      }
    }

    stage('Build & Tag Docker Image') {
      steps {
        dir('project') {
          // Ensure the WAR file exists in target/ directory
          sh 'docker build -t project1 -f Dockerfile .'
        }
      }
    }
  }
}
