FROM ubuntu 
MAINTAINER sigma
LABEL "Genz"="90s kid"
COPY abc.sh /var/
RUN apt-get update
ENTRYPOINT ["echo","entada booli makla"]

#docker run -it <name> shootmaadbeeka prints whole sentence entada booli makla shootmaadbeeka
#appendng is done (if instead of ENTRYPOINT we use CMD and gives the same ["echo","entada booli makla"] ) while runtime we give shootmaadbeeka then only the latest is being printed



