pipeline { 
  agent any
  
  tools {
    jdk 'java-11'
    maven 'maven'
  }
  
  stages {
    stage('Git Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/anooptm1999/git-practice.git'
      }
    }

    stage('Change Directory') {
      steps {
        dir('subdirectory-name') {  // Change to the directory where the pom.xml is located
          sh 'mvn compile'
          sh 'mvn clean install'
        }
      }
    }
  }
}
