pipeline { 
  agent any
  
  tools {
    jdk 'java-11'
    maven 'maven'
  }
  
  stages {
    stage('Git Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/anooptm1999/git-practice.git'
      }
    }

    stage('Change Directory') {
      steps {
        // Change to the directory where the pom.xml is located
        dir('project') {  // Adjust the folder name to match where your pom.xml is located
          sh 'mvn compile'
        }
      }
    }

    stage('Build') {
      steps {
        dir('project') {
          sh 'mvn clean install'
        }
      }
    }

    stage('Build & Tag Docker Image') {
      steps {
        // Docker build and tag command
        sh 'docker build -t project1 .'
      }
    }
  }
}
