pipeline { 
  agent any
  
  tools {
    jdk 'java-11'
    maven 'maven'
  }
  
  stages {
    stage('Git Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/anooptm1999/git-practice.git'
      }
    }

    stage('Verify POM') {
      steps {
        sh 'ls -l'  // List directory contents to verify pom.xml is present
      }
    }

    stage('Change Directory') {
      steps {
        // Change to the directory where the pom.xml is located
        dir('subfolder-name') { // Replace with the actual subfolder name if needed
          sh 'mvn compile'
        }
      }
    }

    stage('Build') {
      steps {
        // Again, change to the directory where the pom.xml is located, if needed
        dir('subfolder-name') { 
          sh 'mvn clean install'
        }
      }
    }
  }
}
